[vibe]
title = "VIBE ─ 온스테이지"
url = "https://vibe.naver.com/onstage/season/2"
entrySelector = "ul.list li.item"
titleSelector = "strong.item_title"
linkSelector = "a.link_textarea"
contentSelector = "a p.desc"
waitForSelector = "li.item"

[vibe_recent]
title = "VIBE ─ 온스테이지"
url = "https://vibe.naver.com/onstage/season/2"
entrySelector = "div.section_intro div.video_info"
titleSelector = "div.main_text.custom_font.scrollmagic.animated a.title"
linkSelector = "div.button_area a.link_detail.scrollmagic.animated"
contentSelector = "div.main_text.custom_font.scrollmagic.animated p.desc"
waitForSelector = "div.video_info"

[vlive]
title = "ONSTAGE (온스테이지)"
url = "https://www.vlive.tv/channel/E61323/board/4268?lang=ko"
entrySelector = "li[class^='post_item']"
titleSelector = "strong[class^='title_text']"
linkSelector = "a[class^='post_area']"
imageSelector = "span[class^='covered_image']"
contentSelector = "span[class^='upload_time']"
waitUntil = "networkidle"

[navertv]
title = "ONSTAGE (온스테이지)"
url = "https://tv.naver.com/onstage/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
